### ISSUE TITLE
28/03 Meeting to select the final idea 

### ISSUE THREAD

**Issue by JulietteB-cri** [iGEM-Bettencourt-2021/Wet-Lab#21]
During this meeting, the team is going to select the idea based on the research we have been doing for the past week on the 2 main idea. 
Note: If one of the main 2 ideas is not considered as relevant as expected, the team will be reading about the backup ideas instead that were selected on the 20/03/2021. 
https://drive.google.com/drive/u/0/folders/179qdct7jAxSTCkugc8tusN6BteiFPp4a

**Comment by research555** [comment]
Little update + closing this issue would be good
