### ISSUE TITLE
Biosensor overview

### ISSUE THREAD

**Issue by SarahHagg** [iGEM-Bettencourt-2021/Wet-Lab#25]
**Lighting Up Biosensors: Now and the Decade To Come** (2019)
Frances S. Lingler and J. Justin Gooding
DOI: 10.1021/acs.analchem.9b00793

Optical biosensors =  portable optical devices that use biorecognition molecules to interrogate a sample for the presence of a target.

worldwide biosensor market is growing at a rate of 9−10% per year and is expected to increase to $27 billion by 2022

Electrochemical (e.g. glucose monitoring) vs optical biosensors (e.g. diagnostics, environmental monitoring, biomanufacturing, and food safety)

Lateral flow assays (pregnancy tests, heart attacks, water pollutants, drugs of abuse, and biological warfare agents)

Abbott, for example, is selling a variety of tests, including HIV, influenza, and cardiometabolic markers

Food testing in particular needs to be fast,  inexpensive and capable of analyzing large, heterogeneous samples.

biosensors that are sensitive for bacteria have been available for over a decade, testing is still generally done in core laboratories in order increase bacterial concentration through sample preculture

Antibody-based lateral flow devices to detect peanuts and gluten that are designed for home use are available already

Drinking water testing: Optical microfluidic sensors for detecting pollutants and the water-borne parasite cryptosporidium re commercially available (nanoparticle based)

noninvasive optical methods for continuous measurement of bodily functions, including pulse, oxygenation, glucose utilization, and lactate generation

Förster resonance energy transfer, extended lifetime fluo- rescence, or upconverting luminescence

use of cell phone cameras as biosensor readout devices has exploded: testing for drugs of abuse in saliva and infectious diseases in clinical fluids; several cell phone readers already on the market.

Identification of targets based on oligonucleotide sequences has long been a biosensor focus

Portable optical biosensors that can both extract and sequence DNA or RNA cannot be far behind

molecular recognition: methods for screening binding molecules, such as aptamers, peptides, and antibodies

recognition molecules have been cloned onto scaffolds that control valency, include groups such as His tags or biotin for subsequent purification or integration with detection schemes, or integrate regions such as hairpin structures that generate conformational responses to binding.

Biosensors:
- Point-of-care diagnostics: reducing health care costs for everyone
- Simple imaging devices will measure specific functions in living tissues to monitor regenerative medicine, cancer therapies, and physical rehabilitation
- high-resolution, hand-held imaging systems: development of new biocompatible recognition molecules
- Wearable optical sensors will rapidly adapt to new applications for health monitoring
- Networked biosensors  for monitoring geographically distributed factors such as epidemics, environmental pollution, animal health, and even crop productivity
- Continuous monitoring devices: integrated into urban infrastructure to monitor delivery of safe drinking water  and food supplies.

**Comment by nathaliaraquelx** [comment]
More on wearable biosensors: https://wyss.harvard.edu/news/wyss-team-wins-top-prize-for-wearable-synthetic-biology-sensors/
