### ISSUE TITLE
Artificial cells 

### ISSUE THREAD

**Issue by nathaliaraquelx** [iGEM-Bettencourt-2021/Wet-Lab#27]
### **From deterministic to fuzzy decision-making in artificial cells**
https://doi.org/10.1038/s41467-020-19395-4

_Introduction:_

“Decisions on a cellular level are made by regulatory proteins that integrate information from the environment and elicit a response by modulating RNA and protein production[...] Theoretical considerations suggest that a decision becomes exponentially more stable as the copy number of regulatory elements, hence metabolic load, increases”.

_Results/Methodology:_

In a cell-free system, they wanted to recreate the genetic regulatory network of bacteriophage λ by building a latch circuit that could activate either of the promoters encoding for Cro and CI proteins and retain memory of the active promoter until toggled.

> 

> ![image](https://user-images.githubusercontent.com/63516633/112472366-f2854b80-8d64-11eb-9445-69b1529670e7.png)

To  toggle  the  promoter  activities,  they  used  a temperature-sensitive CI (CIts) mutant that could tune its deactivation rate with a rise in temperature from 30 °C (no deactivation) to 41°C (fast deactivation).

- They placed the gene coding for green fluorescent protein (GFP) in tandem with the Cro gene, as a reporter of the activity of the strong PRpromoter,  and  recorded  the  signal  using  epi-fluorescence microscopy. The strong PRpromoter increased the GFP signal over the background fluorescence of the elastomer used to create the compartments. It was observed smooth GFP dynamics with a high signal to noise ratio, peaking after ~2 h and slowly reaching steady-state values after two more hours.

_Conclusion/Discussion:_

They concluded that,

- “The protein production is balanced by the removal (degradation, dilution, and deactivation) to reach steady-state copy number that can give an estimate of how long a decision takes. For the high-copy number regime, the removal of many molecules down to the threshold value where the genetic regulatory network can flip the switch takes longer. Hence, the speed of decision-making reduces with a larger steady-state copy number, while the accuracy increases due to the averaging over many molecules.
Our Findings in isolated artificial cells may also shed light on the tolerance of living cells for fuzzy, but timely decision-making”

**Comment by research555** [comment]
Whats this supposed to be?
