### ISSUE TITLE
14/03 Meeting #3 Vote results and discussion to select 3-5 ideas

### ISSUE THREAD

**Issue by JulietteB-cri** [iGEM-Bettencourt-2021/Wet-Lab#3]
Next step for the wet lab is sunday morning session to look at the score of the ideas: take the first 25-35% and brainstorm a bit about them to select 3-5 by the end of the meeting

**Comment by research555** [comment]
Just a comment, you don't need to move issues from to do to done, it does this automatically when you close an issue!
