### ISSUE TITLE
Artificial Cell Membrane Systems for Biosensing Applications

### ISSUE THREAD

**Issue by Zoepin** [iGEM-Bettencourt-2021/Wet-Lab#33]
For the second half of the week, I am looking more into biosensors.
This paper is very oriented towards chemistry and electronics but I believe is of value. It gives insight on a different type of biosensors, artificial cell membranes.

# Artificial Cell Membrane Systems for Biosensing Applications
https://pubs.acs.org/doi/full/10.1021/acs.analchem.6b04744

### Why use biological membranes as biosensors?
Because the biological membrane engages in almost every communication between cell/organelle and it's surroundings, membrane-associated proteins and lipid molecules have become a significant focus of efforts to identify new pharmaceutical drug targets.
Furthermore, the functionality of the biological membrane makes it ideal for biosensing applications, as it inherently fulfils the necessary conditions of a sensor.

### What is an artificial biosensor membrane?
- Lipid vesicles, which encapsulate an aqueous  phase
- Planar  membrane system, which can be further classified into supported bilayers, suspended bilayers, and nanodiscs.

This review focuses on membrane biosensor platforms that use suspended lipid bilayers coupled with electrical detection technologies. The suspended bilayer, also known as a free-standing bilayer, electrically divides two aqueous chambers.  By  insertion  of  transmembrane  proteins  as  the  sensing  elements,  the  suspended  bilayers  form  versatile  chemical  sensing  systems  that  are  compatible  with  electronics

### Fundamentals of lipid bilayer systems (biological and artificial)
Phospholipids (amphiphilic molecules) that organize themselves in the form of a bilayer in aqueous solution. Typical  phospholipids  have  a  molecular  weight  of  approximately  1  kDa,  and  form  a  bilayer  of  5-nm  thickness.
Able to suppress the permeation of water-soluble molecules
High membrane resistance of over 1 MΩ·cm2
Permeability to sodium ions

### Formation of bilayers
Using microfluidics
- The  Behrends  group  automated a method and the products are commercialized by Nanion Technologies
- Droplet contact method

### Protein insertion into a lipid bilayer platform
Pore-forming toxins (gramicidin,  alamethicin,  and  α-hemolysin) are soluble as monomers.
=> spontaneously  bind  to  the  lipid  bilayer  membrane  and  form  transmembrane  pores
Insoluble proteins =>reconstituted  into  lipid  vesicles  before  insertion  into  the  bilayer  membrane

### Membrane pore biosensors
**Nanopore coupled to an enzyme sensors for DNA sequencing**
The  enzyme,  such  as  a  polymerase  or  helicase,  binds  to  the  DNA  and “ratchets” the DNA through the nanopore. This significantly slows the translocation velocity down to a few tens of milliseconds per base, which is an adequate dwell time to allow single-nucleobase discrimination. 

**Nucleotide sequence within a nanopore for diagnosis and analysis**
The  presence  of  a  target  sequence  is  discriminated  using  complementary  sequences  within  the  nanopore.
One  application  of  this  is  in  the  diagnosis  of  tumor-derived  circulating  microRNAs.

** Pore-based chemical sensor to detect ions, organic molecules, peptides and even larger molecules such as viruses.**

_The article goes more in depth in how the different systems work, their limitations and possible improvements._

### Future directions
- The  applications  could  be  used  to  detect  biomarkers  from  body  fluids  and  for  VOC  (volatile  organic  compound)  analysis,  including  exhaled  gas  diagnostics,  odorant  sensors,  explosives,  noxious  gas,  and  illegal  drug  detectors. 
- For diagnostic use,lLigand-gated ion channels will become one of  the  model  sensor  elements,  since  they  can  recognize  single  molecules  with  a  given  specificity  and  sensitivity,  and  transduce  molecular  binding  events  to  an  ionic  current  that  is  compatible  with  electronic  devices.

**Comment by research555** [comment]
If i got this right then it is just a lipid nanoparticle with a transmembrane protein right?

**Comment by Zoepin** [comment]
Yes that is right.
The basic structure is a lipid bilayer or vesicle. Those can be produced using microfluidics or bought from producing companies.
The lipid structure is then 'customed' by adding one or various proteins to reach a specific goal. This paper is mostly about pores and nanopores but other proteins can be added to form complex cell membranes.
That way, a biological membrane can be more or less mimicked or the complexe can be used for a completely different application. For example, the paper develops an idea on sequencing.
