### ISSUE TITLE
Some comments for the team

### ISSUE THREAD

**Issue by research555** [iGEM-Bettencourt-2021/Wet-Lab#34]
I'm not going to read a block of text that isn't visually appealing and you can bet that others won't either. Use bullet points, use headers, just make it look presentable. @Sophlei the summary was so good but I have so much trouble reading it because its all block text. Remember that other people are reading these, not just you. This goes for everyone though, but @Zoepin is doing a good job.

Also @nathaliaraquelx @git-cgalan @KaroGu @camilaball none of you have produced anything this week. This is not okay. I expect you all to pull yourselves together today. We don't have time for this. You are putting the burden of finding viable research topics on your 3 people in your team and it's not acceptable. Get it together, do some research, and post it on GitHub by 11 today.

**Comment by JulietteB-cri** [comment]
No feedbacks for me?

**Comment by research555** [comment]
Haha, you have been good too. It's just important that you hold people accountable for their lack of involvement. I don't want to always be the buzz kill

**Comment by camilaball** [comment]
Sorry guys I forgot to update the Github :/ ! I'll do it now
