### ISSUE TITLE
Can someone read this paper?

### ISSUE THREAD

**Issue by research555** [iGEM-Bettencourt-2021/Wet-Lab#36]
I've read it three times, highlighted many different sentences and I still dont understand a single word of what is going on. Can one of you assign yourselves to have a crack at it?

https://www.nature.com/articles/nature12148

**Comment by JulietteB-cri** [comment]
From my first lecture - I will complete it after my future relecture. 

- They performed analog computations with only a few biological parts of a living cells
- You can build a ratiometer with 2 or 3 TF
- You can use digital circuits to integrate sensors and respond to environmental conditions and analogue circuits to do arithmetic functions with a small number of regulators
- They did logarithmically linear computation in biochemical systems (energy efficient), can be applied to brain circuits. 
- You can implement PF in circuits such as cortical circuits - that follows the Weber law
- PF are essential to increase the log-linear dynamic range of operations

**Comment by Zoepin** [comment]
I just read the abstract and faced my first big question: what is Weber's law?

Weber’s law is a historically important psychological law quantifying the perception of change in a given stimulus. The law states that the change in a stimulus that will be just noticeable is a constant ratio of the original stimulus. It has been shown not to hold for extremes of stimulation.
https://www.britannica.com/science/Webers-law

**Comment by JulietteB-cri** [comment]
Small additions to my first reading that I think are relevant 

Why analog? 
* because compared to digital computation, this computation mode is more efficient in terms of speed, energy consumption.... 

How can we reduce the variation of cross-over precision due to computation? 
* Using feedbacks loops or signal averaging to increase precision for example
