### ISSUE TITLE
Blueprints for Biosensors: Design, Limitations, and Applications (Carpenter, Alexander, et al. 2018)

### ISSUE THREAD

**Issue by KaroGu** [iGEM-Bettencourt-2021/Wet-Lab#43]
_**Carpenter, Alexander, et al. “Blueprints for Biosensors: Design, Limitations, and Applications.” Genes, vol. 9, no. 8, July 2018, p. 375. DOI.org (Crossref), doi:10.3390/genes9080375.**_

The article discusses the design of several classes of biosensors taking into account their advantages and limitations based on their properties.

_They identify three main areas of application:_ 

- Group Diagnostics: Environmental, agricultural and industrial applications: for example, quality assurance in food production, detection of organic/inorganic contaminants, detection of wide range of nutrients to aid in harvest time optimization, bioprocesses surveillance, etc. Also, some interest was brought in biosensors assessing water quality for example after fish death. Usually main ‘requirements/themes’ for group diagnostics are: the frequency of sampling is periodic, turnaround time can vary between several hours to several days, detection does not necessarily needs to be done ‘on site’ 
- Point – of – Use Diagnostics: medical and security applications: for example disease/pathogen diagnostics or screening for dangerous materials. Main features of point in use diagnostics include that they need to have rapid response times, be mobile (preferably handheld), require low technical experience to operate, and be cost effective to mass produce and implement in high traffic environments (hospitals, transit hubs, events, etc.)
- Single-Cell Diagnostics: Metabolic Engineering, and Synthetic Biology Applications: biosensors need to be able to survey and respond to the target ligand concentration within individual cells without being impacted by other population members. This makes biosensors developed for single cell diagnostics significantly less tolerant to false positive/negative activation compared to other applications

_In the article they consider 3 main groups of biosensors_

- _Transcription Factor - Based biosensors (TFB)_
    - **Native Transcription Factor – Based biosensors:** easiest to engineer and most widely used since are based on naturally occurring transcription factors.  Commonly used output signals with these biosensors include fluorescence, antibiotic resistance, increased growth rate, bioluminescence. When there are no known transcriptional regulatory elements that respond to the target ligand, in some cases it can be mitigated using dose response transcriptomics or via insertional mutagenesis. One of the major limitations to this type of biosensor construction is the range of transcription factor promoter pairs available.
    - **Heterologous Species Transcription Factor – Based Biosensors:** if transcriptional regulators for a target ligand do not exist in the desired host species, using transcriptional regulators from other species can be a valuable solution. Design involves codon optimization of the identified transcription factors, and biosensor tuning by modulating promoters length/binding domain lengths and copy number. Transcriptional inhibition easier than transcriptional activation.  However, it is not always an option, especially if it attempted across domains of life. Construction is generally reliant on known transcriptional activators with well – characterized mechanisms. 
    - **Modular Transcription Factor – Based Biosensors:** involves the use of modular protein domains to induce transcription in response to target ligand. The critical components in this type of biosensor construction are protein domains that dimerize/co-ordinate with each other in the presence of a target ligand. Limitations: finding/creating ligand binding domains that either dimerize or produce useful conformational change upon ligand association can be more difficult -> more complicated protein engineering. To enhance this technique would require that binding proteins/peptides be generated using random selection techniques such as phage/yeast display or two hybrid system. 
    
- _Nucleic Acid – Based Biosensors_
    - **Aptamers** – single stranded DNA or RNA molecules that have affinity to target ligand. The most constraining factor in aptamer biosensor development is the identification of single stranded DNA/RNA sequences that bind specifically to the target ligand. Limitations: how the SELEX process is applied to small molecules. Unlike protein targets, small molecule targets need to be immobilized prior to incubation with the aptamer library. 3D structures are highly influenced by the surrounding conditions, such as pH and temperature. Could make compatibility across assay systems difficult.
    - Riboswitches - class of biosensors made of single stranded RNA. Composed of two joined RNA domains, the first is aptamer that binds to the target ligand, second is a response domain to generate output. Limitations: its ability to integrate aptamer domains with response domains to generate functional riboswitches. The criteria that are necessary for identifying which aptamers will make good riboswitches are not fully understood
- _Transcription – Independent Protein – Based Biosensors_  
    - **Integrated TIPB** – receptor domain/s for a target ligand are expressed as a fusion protein with little to no linker domain to a response domain. Most closely mimics natural enzymes/signaling proteins. Advantages – can generate very selective activity with large linear and dynamic ranges. One of the limitations is the background knowledge since most integrated TIPBs are made using known protein domains. Additionally, design process is not trivial and rather complicated.  One of biggest limitations is that integrated TIPBs are designed in a finite solution space, meaning that chances of success rely on very specific circumstances.
    - **Semi modular TIPB** - involve using linkers to coordinate receptor and response domain activity in response to the target ligand. Advantages: higher degree of engineering possibilities than fully integrated designs. Limitations: optimal linker length/composition is difficult to know a priori. Additionally, often many different linker configurations need to be tested before an optimal sensor is generated. Design choices of linker require a moderate degree of specialized skill. 
    - **Modular TIPB** - use protein tethers for receptor domain induced co-localization of response domains. Tethers do not use conformational changes to induce response but allow the recruitment of all necessary signaling components into one location.  Construction is simpler than semi – modular TIPB or integrated TIPB. Also, there is fewer constraints when building a design. Limitations for the design strategy include baseline activation and choice of response. Since the only barrier to activation is co-localization, stochastic movement of sensor components is more likely to influence biosensor output and thus there might be more noise and decreased sensitivity. 

_Sensors’ ‘applicability’:_

- For group diagnostics: 
    - TFBs could be used since they are easy to design, however would need to take response time into consideration. 
    - Nucleic acid-based biosensors are a very good choice (can be easily developed for a wide range of applications + satisfies the time scale and location requirements for most group diagnostic applications).
    -  TIPBs well suited for group diagnostics: excellent sensitivity and specificity. Wide range of possible targets and signal outputs

- Point – of – Use Diagnostics: 
    - TFBs take too long to respond. 
    - Nucleic acid-based biosensors also not a particularly good choice. 
    - TIPB showed great promises for point – of – use diagnostics - rapid response time and sensitivity, relatively high stability. 
- Single cell diagnostics: 
    - TFBs: major advantage: natural interface with transcriptional output within a single living cell. Also these types of biosensors has a natural capacity for signal amplification, making them highly sensitive for changes in ligand concentration. Widely applicable for metabolic engineering.
    - RNA aptamers, riboswitches -> good 
    - TIPBs: lack of transcriptional output. Makes it more difficult to incorporate into genetic circuits

**Comment by nathaliaraquelx** [comment]
Those TIPBs reminded me of the "Two-Component Regulatory Systems", which mediate signal transduction in bacteria.
