### ISSUE TITLE
Aptamer Sensors (Marrazza et al., Man et al. 2021, Wu et al 2019)

### ISSUE THREAD

**Issue by SarahHagg** [iGEM-Bettencourt-2021/Wet-Lab#44]
### **Aptamer Sensors** 
Giovanna Marrazza - DOI: 10.3390/bios7010005

**Aptamers** 
- single-stranded DNA or short RNA sequences
- isolated in vitro from a library of synthetic oligonucleotides according to heir affinity toward a target molecule (with SELEX)

**Advantages of aptamers vs antibodies**
- high stability
- low dimension
- high affinity for small molecules
- easy to synthesize in vitro, simple to modify
     -> efficient, exceptional binding constants in the micromolar to picomolar range

**Some applications of aptamers as biosensors**
- recognition of proteins and as enzyme mimics (Menger et al.)
- detection of intact viruses  (P. K. R. Kumar)
- detection of thrombin and vascular endothelial growth factor biomarkers and aflatoxin M1 with 'whispering gallery mode resonators (WGMRs)' (Nunzi Conti et al.)
- protein biomarker analysis using electrochemichemistry electrochemiluminescence and photoelectrochemical transduction methods (Ravalli et al.)
- gluten quantification: aptamer-protein and aptamer-peptide interactions (Miranda-Castro et al.)

**Comment by SarahHagg** [comment]
### **A microfluidic colorimetric biosensor for in-field detection of Salmonella in fresh-cut vegetables using thiolated polystyrene microspheres, hose-based microvalve and smartphone imaging APP**
Yan Man et al. (2021) 
_DOI: 10.1016/j.foodchem.2021.129578_

looks really cool, but cannot access the full article :/

- Salmonella was detected with Aptamer-PS-cysteamine conjugates 
- gold nanoparticles aggregated on the surface of Salmonella-aptamer-PS-cysteamine conjugates
-> resulting in a visible color change in the detection chamber
- smartphone imaging app for monitoring colorimetric signals

![1-s2 0-S0308814621005847-ga1_lrg](https://user-images.githubusercontent.com/64137549/112631833-ad7e1980-8e37-11eb-9b79-646c27e169dc.jpg)

**Comment by SarahHagg** [comment]
### **A novel colorimetric aptasensor for detection of chloramphenicol based on lanthanum ion–assisted gold nanoparticle aggregation and smartphone imaging**
Yang-yang Wu et al. (2019)
_DOI: 10.1007/s00216-019-02149-7_

similar approach to use aptamers for detection, resulting in a color change that can be detected with an app

- detection of chloramphenicol (CAP)
- ssDNA-modified gold nanoparticle (AuNP) aggregation (facilitated with lanthanum (La3+) ions)
- color change from blue to violet-red when CAP is present -> app

colorimetric aptasensors better than with fluorescence, electrochemical or quartz crystal microbalance, as they do not depend on a special analysis device -> easy on-site analyses

**use of metal ions (e.g. lanthanum):**
- metal ions can strongly combine with the phosphate groups of aptamers specifically through coordination interactions 
-> aggregation of AuNPs in absence of CAP 
-> color change from red to blue
- aggregation of La3+-Apt-AuNPs **avoided false positives** phenomenon from AuNP aggregation induced by the salt conditions and the interference of other substances in food.

**in presence of CAP:** 
Apt-CAP complex 
-> La3+ attachment deprived 
-> no aggregation of AuNPs
-> AuNP color change to violet-red

<img width="890" alt="Screenshot 2021-03-26 at 14 07 35" src="https://user-images.githubusercontent.com/64137549/112635899-aa395c80-8e3c-11eb-8307-1a1e4b4e9761.png">

**Comment by nathaliaraquelx** [comment]
Wow, this type of imaging detection is really interesting.

**Comment by git-cgalan** [comment]
The protocol look super cool an easy to apply to another project
