### ISSUE TITLE
Types of relay

### ISSUE THREAD

**Issue by Zoepin** [iGEM-Bettencourt-2021/Wet-Lab#53]
### Google Doc to gather our ideas

I created a Google Doc with my findings on the types of existing relays in synthetic cell-to-cell circuits.
If you want, feel free to check it out and add your own findings.

https://docs.google.com/document/d/1yNH_fxmAaXBpEgDm3AgIO8s7hmXbEipXPDATlGh_Fu0/edit#

**Comment by JulietteB-cri** [comment]
Thank you, I'll add try to add the one I find before the end of the day as well!

**Comment by Zoepin** [comment]
To record our findings, I was thinking of using this document and GitHub:
- this document could gather our references
- GitHub would allow further development of these ideas like last week.

What do you think?
